"""empty message

Revision ID: 1dae0b44870c
Revises: a14e1557f5af
Create Date: 2021-01-20 18:23:00.802063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dae0b44870c'
down_revision = 'a14e1557f5af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'refundable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'refundable',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
