"""empty message

Revision ID: 59096e995a19
Revises: 
Create Date: 2021-01-29 21:48:28.468365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59096e995a19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'refundable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('user', 'telefono')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telefono', sa.INTEGER(), nullable=True))
    op.alter_column('product', 'refundable',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
