"""empty message

Revision ID: 91a109925bae
Revises: 1dae0b44870c
Create Date: 2021-01-27 09:49:05.387313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a109925bae'
down_revision = '1dae0b44870c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'refundable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('user', 'telefono')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telefono', sa.INTEGER(), nullable=True))
    op.alter_column('product', 'refundable',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
