"""empty message

Revision ID: a14e1557f5af
Revises: f5decbeee2de
Create Date: 2021-01-20 18:17:32.161680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14e1557f5af'
down_revision = 'f5decbeee2de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'refundable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'refundable',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
