"""added image field to the product table

Revision ID: e33663a47dc8
Revises: 
Create Date: 2020-11-19 18:28:22.635818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33663a47dc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image', sa.String(length=500), nullable=True))
    op.alter_column('product', 'refundable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'refundable',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('product', 'image')
    # ### end Alembic commands ###
