"""add user

Revision ID: f5decbeee2de
Revises: 
Create Date: 2021-01-20 18:14:20.432545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5decbeee2de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'refundable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'refundable',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
